# .github/workflows/publish-npm.yml

name: Publish Package to npm

on:
  push:
    tags:
      - "v*" # Triggers on tags like v1.0.0, v0.1.0-beta, v2.3.4 etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Permission to read the repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # Or a specific Bun version if needed

      - name: Install dependencies
        run: bun install --frozen-lockfile # Ensures use of versions from bun.lockb

      # The 'bun run build' step is executed by the 'prepare' script in package.json,
      # which 'bun publish' runs automatically when not given a tarball.

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=$(echo $GITHUB_REF_NAME | sed 's/v//')" >> $GITHUB_OUTPUT

      - name: Determine npm dist-tag
        id: npm_dist_tag
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          if [[ "$VERSION" == *-* ]]; then
            # For versions like 1.0.0-beta.1, use 'beta' as the tag
            # For versions like 1.0.0-alpha.0, use 'alpha' as the tag
            # Extracts the first part of the prerelease identifier
            echo "DIST_TAG=$(echo $VERSION | awk -F'-' '{print $2}' | awk -F'.' '{print $1}')" >> $GITHUB_OUTPUT
          else
            # For stable versions like 1.0.0, use 'latest'
            echo "DIST_TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Verify tag matches package.json base version
        run: |
          TAG_VERSION="${{ steps.get_version.outputs.VERSION }}"

          # Get package.json version
          echo "console.log(require('./package.json').version);" > get_pkg_version.js
          PACKAGE_JSON_VERSION=$(bun run get_pkg_version.js)
          rm get_pkg_version.js

          # Extract base version from tag (everything before first '-')
          TAG_BASE_VERSION=$(echo "$TAG_VERSION" | awk -F'-' '{print $1}')

          echo "Git Tag: $TAG_VERSION"
          echo "Tag Base Version: $TAG_BASE_VERSION"
          echo "package.json Version: $PACKAGE_JSON_VERSION"

          # Validate that tag base version matches package.json
          if [ "$TAG_BASE_VERSION" != "$PACKAGE_JSON_VERSION" ]; then
            echo "Error: Tag base version ($TAG_BASE_VERSION) does not match package.json version ($PACKAGE_JSON_VERSION)."
            echo "Valid tags for v$PACKAGE_JSON_VERSION: v$PACKAGE_JSON_VERSION, v$PACKAGE_JSON_VERSION-beta.1, v$PACKAGE_JSON_VERSION-dev, etc."
            exit 1
          fi

          echo "✓ Tag base version matches package.json"

      - name: Update package.json version to match tag
        run: |
          TAG_VERSION="${{ steps.get_version.outputs.VERSION }}"
          echo "Updating package.json version to $TAG_VERSION"

          # Use node to update package.json version
          node -e "const fs=require('fs'); const pkg=require('./package.json'); pkg.version='$TAG_VERSION'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');"

          echo "✓ Updated package.json version to $TAG_VERSION"

      - name: Publish to npm with Bun
        # 'bun publish' will use the version from your package.json.
        # The --tag flag here sets the npm distribution tag.
        run: bun publish --tag ${{ steps.npm_dist_tag.outputs.DIST_TAG }} --access public
        env:
          # Bun publish respects NPM_CONFIG_TOKEN for authentication
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
